name: Generate Playlist

on:
  push:
    paths:
      - 'music/songs/**'
  pull_request:
    paths:
      - 'music/songs/**'

jobs:
  generate-playlist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run playlist generator
      run: node music/generate-playlist.js
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-generate playlist"
        git push
